# Make r refresh the config
unbind r
bind r

# Set leader key to ctrl s
set -g prefix C-s

# Activate Mouse
set -g mouse on

# Bind hjkl to left down up right
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Set bar top
set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
#Gruvbox theme
set -g @plugin 'egel/tmux-gruvbox'

# display path and enhance section with other plugin
set -g @tmux-gruvbox-right-status-z '#{pane_current_path} #{tmux_mode_indicator}'

run '~/.tmux/plugins/tpm/tpm'
